### ISSUE TITLE
Xteve fatal error on Updating Database

### ISSUE THREAD

**Issue by ambersnow** [xteve-project/xTeVe#151]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Suddenly the xteve server can't start and fails immediately after the Updating Database step, restoring from backups, deleting cache/data directories and rolling back to v2.1.0 does not fix it.

The server will start if I delete the entire configuration and start from scratch but the moment I go past the XMLTV link step it crashes the server and I cannot continue with configuration and rebooting the server causes it to crash immediately on start up.

**Server (please complete the following information):**
- OS: Linux
- Arch: 64bit
- xTeVe 2.1.0 and 2.1.2 (docker container by dmcallejo)

**To Reproduce**
Start the server

**Expected behavior**
The server should be able to update the database or gracefully tell me what the issue is so I can try and fix it.

Both of the following logs are from my attempts on using v2.1.0 but the same errors and log occurs when I use v2.1.2 as well.

**Log from startup**
```

E2020/06/17 03:30:40 [xTeVe] Version:               2.1.0 Build: 0100,
For help run: /usr/local/bin/xteve -h,
2020/06/17 03:30:40 [xTeVe] Database Version:      2.1.0,
2020/06/17 03:30:40 [xTeVe] System IP Addresses:   IPv4: 2 | IPv6: 0,
2020/06/17 03:30:40 [xTeVe] Hostname:              48f1d07cb7ca,
2020/06/17 03:30:40 [xTeVe] System Folder:         /data/,
2020/06/17 03:30:40 [xTeVe] Load Settings:         /data/settings.json,
2020/06/17 03:30:40 [xTeVe] Temporary Folder:      /tmp/xteve/2020-06-OCBS-WO0LJD/,
2020/06/17 03:30:40 [xTeVe] GitHub:                https://github.com/xteve-project,
2020/06/17 03:30:40 [xTeVe] Git Branch:            master [xteve-project],
2020/06/17 03:30:40 [xTeVe] SSDP / DLNA:           true,
2020/06/17 03:30:40 [xTeVe] Update Available:      Version: 2.1.2.0121,
2020/06/17 03:30:40 [xTeVe] Update Server:         GitHub,
2020/06/17 03:30:40 [xTeVe] Start Update:          Branch: master,
2020/06/17 03:30:40 [ZIP] New version (xteve_2): 2.1.2.0121,
2020/06/17 03:30:40 [ZIP] Download new version...,
2020/06/17 03:30:40 [xTeVe] [ERROR] open /usr/local/bin/xteve: permission denied (Update failed) - EC: 6002,
2020/06/17 03:30:40 [xTeVe] UUID:                  2020-06-OCBS-WO0LJD,
2020/06/17 03:30:40 [xTeVe] Tuner (Plex / Emby):   4,
2020/06/17 03:30:40 [xTeVe] EPG Source:            XEPG,
2020/06/17 03:30:40 [xTeVe] Plex Channel Limit:    480,
2020/06/17 03:30:40 [xTeVe] Backup Path:           /data/backup/,
2020/06/17 03:30:40 [xTeVe] Backup file:           /data/backup/xteve_auto_backup_20200617_0330.zip,
2020/06/17 03:30:40 [xTeVe] Download:              [feed],
2020/06/17 03:30:40 [xTeVe] Header filename:       liveTV.2020.06.17.m3u,
2020/06/17 03:30:40 [xTeVe] Check File:            [feed],
2020/06/17 03:30:40 [xTeVe] Save File:             [feed] [ID: MPB05B5JAPGHW2P10QQT],
2020/06/17 03:30:40 [xTeVe] Download:              http://www.xmltv.co.uk/feed/3364,
2020/06/17 03:30:41 [xTeVe] Check File:            http://www.xmltv.co.uk/feed/3364,
2020/06/17 03:30:41 [xTeVe] Save File:             http://www.xmltv.co.uk/feed/3364 [ID: XUH0C68EH5LLB1AWHBQ0]
2020/06/17 03:30:41 [xTeVe] All streams:           135,
2020/06/17 03:30:41 [xTeVe] Active streams:        135,
2020/06/17 03:30:41 [xTeVe] Filter:                0,
2020/06/17 03:30:41 [xTeVe] XEPG:                  Parse XMLTV file: XMLTV,
2020/06/17 03:30:41 [xTeVe] XEPG:                  Update database,
* * * * * FATAL ERROR * * * * *,
OS:   linux,
Arch: amd64,
Err:  assignment to entry in nil map,
panic.go:680 runtime.gopanic,
map_faststr.go:204 runtime.mapassign_faststr,
xepg.go:433 _/root/src.createXEPGDatabase,
xepg.go:78 _/root/src.buildXEPG,
config.go:254 _/root/src.StartSystem,
xteve.go:195 main.main,
proc.go:212 runtime.main,
asm_amd64.s:1358 runtime.goexit,
* * * * * * * * * * * * * * * *
```

**Log from crash from clean configuration**
```
2020/06/17 03:29:24 [xTeVe] Version:               2.1.0 Build: 0100,
2020/06/17 03:29:24 [xTeVe] Database Version:      2.1.0,
2020/06/17 03:29:24 [xTeVe] System IP Addresses:   IPv4: 2 | IPv6: 0,
2020/06/17 03:29:24 [xTeVe] Hostname:              48f1d07cb7ca,
2020/06/17 03:29:24 [xTeVe] System Folder:         /data/,
2020/06/17 03:29:24 [xTeVe] Load Settings:         /data/settings.json,
2020/06/17 03:29:24 [xTeVe] Temporary Folder:      /tmp/xteve/2020-06-OCBS-WO0LJD/,
2020/06/17 03:29:24 [xTeVe] GitHub:                https://github.com/xteve-project,
2020/06/17 03:29:24 [xTeVe] Git Branch:            master [xteve-project],
2020/06/17 03:29:24 [xTeVe] SSDP / DLNA:           true,
2020/06/17 03:29:25 [xTeVe] Update Available:      Version: 2.1.2.0121,
2020/06/17 03:29:25 [xTeVe] Update Server:         GitHub,
2020/06/17 03:29:25 [xTeVe] Start Update:          Branch: master,
2020/06/17 03:29:25 [ZIP] New version (xteve_2): 2.1.2.0121,
2020/06/17 03:29:25 [ZIP] Download new version...,
2020/06/17 03:29:25 [xTeVe] [ERROR] open /usr/local/bin/xteve: permission denied (Update failed) - EC: 6002,
2020/06/17 03:29:25 [xTeVe] UUID:                  2020-06-OCBS-WO0LJD,
2020/06/17 03:29:25 [xTeVe] Tuner (Plex / Emby):   1,
2020/06/17 03:29:25 [xTeVe] EPG Source:            PMS,
2020/06/17 03:29:25 [xTeVe] Plex Channel Limit:    480,
2020/06/17 03:29:25 [xTeVe] All streams:           0,
2020/06/17 03:29:25 [xTeVe] Active streams:        0,
2020/06/17 03:29:25 [xTeVe] Filter:                0,
2020/06/17 03:29:25 [xTeVe] DVR IP:                172.17.0.4:34400,
2020/06/17 03:29:25 [xTeVe] Web Interface:         http://172.17.0.4:34400/web/ | xTeVe is also available via the other 1 IP.,
2020/06/17 03:29:50 [xTeVe] Download:              [feed],
2020/06/17 03:29:51 [xTeVe] Header filename:       liveTV.2020.06.17.m3u,
2020/06/17 03:29:51 [xTeVe] Check File:            [feed],
2020/06/17 03:29:51 [xTeVe] Save File:             [feed] [ID: MPB05B5JAPGHW2P10QQT],
2020/06/17 03:29:51 [xTeVe] All streams:           135,
2020/06/17 03:29:51 [xTeVe] Active streams:        135,
2020/06/17 03:29:51 [xTeVe] Filter:                0,
2020/06/17 03:30:00 [xTeVe] Download:              http://www.xmltv.co.uk/feed/3364,
2020/06/17 03:30:00 [xTeVe] Check File:            http://www.xmltv.co.uk/feed/3364,
2020/06/17 03:30:00 [xTeVe] Save File:             http://www.xmltv.co.uk/feed/3364 [ID: XUH0C68EH5LLB1AWHBQ0],
2020/06/17 03:30:00 [xTeVe] XEPG:                  Parse XMLTV file: XMLTV,
2020/06/17 03:30:00 [xTeVe] XEPG:                  Update database,
2020/06/17 03:30:00 http: panic serving 10.1.1.110:58275: assignment to entry in nil map,
goroutine 73 [running]:,
net/http.(*conn).serve.func1(0xc000562000),
	/usr/local/go/src/net/http/server.go:1767 +0x139,
panic(0x873e60, 0xe2b750),
	/usr/local/go/src/runtime/panic.go:679 +0x1b2,
_/root/src.createXEPGDatabase(0xeebdcef0722c8f3f, 0x10),
	/root/src/xepg.go:433 +0x9cd,
_/root/src.buildXEPG(0xc0003d2000),
	/root/src/xepg.go:77 +0x88,
_/root/src.saveWizard(0xc0003d20b0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...),
	/root/src/data.go:721 +0x5da,
_/root/src.WS(0xe3ab60, 0xc0004bc620, 0xc000186000),
	/root/src/webserver.go:523 +0x1256,
net/http.HandlerFunc.ServeHTTP(0xdafe68, 0xe3ab60, 0xc0004bc620, 0xc000186000),
	/usr/local/go/src/net/http/server.go:2007 +0x44,
net/http.(*ServeMux).ServeHTTP(0x111ed20, 0xe3ab60, 0xc0004bc620, 0xc000186000),
	/usr/local/go/src/net/http/server.go:2387 +0x1bd,
net/http.serverHandler.ServeHTTP(0xc0004220e0, 0xe3ab60, 0xc0004bc620, 0xc000186000),
	/usr/local/go/src/net/http/server.go:2802 +0xa4,
net/http.(*conn).serve(0xc000562000, 0xe3ba60, 0xc000564000),
	/usr/local/go/src/net/http/server.go:1890 +0x875,
created by net/http.(*Server).Serve,
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```
**Desktop (please complete the following information):**
 The application crashes before the web interface is available.

Thank you for this awesome app btw. Let me know if I can give anymore info.

**Comment by mar-mei** [comment]
That should be fixed in the current version. Your update fails because xTeVe has no write permission to the folder where the binary is located.
```
2020/06/17 03:29:25 [xTeVe]  [ERROR] open /usr/local/bin/xteve: permission denied (Update failed) - EC: 6002
```

**Comment by ambersnow** [comment]
The issue isn't the self updating, it's in a docker container so it can't write back to its own binary. Running the latest version also has this issue, with the same exact log messages.

**Comment by mar-mei** [comment]
Yes I know. Your log is from an older version. I need the log from the current version. You should check your Docker image or deactivate the xTeVe update function.

**Comment by ambersnow** [comment]
Here's the log from v2.1.2:
```
2020/06/17 14:51:43 [xTeVe] Version:               2.1.2 Build: 0121,
2020/06/17 14:51:43 [xTeVe] Database Version:      2.1.0,
2020/06/17 14:51:43 [xTeVe] System IP Addresses:   IPv4: 2 | IPv6: 0,
2020/06/17 14:51:43 [xTeVe] Hostname:              48f1d07cb7ca,
2020/06/17 14:51:43 [xTeVe] System Folder:         /data/,
2020/06/17 14:51:43 [xTeVe] Load Settings:         /data/settings.json,
2020/06/17 14:51:43 [xTeVe] Temporary Folder:      /tmp/xteve/2020-06-OCBS-WO0LJD/,
2020/06/17 14:51:43 [xTeVe] GitHub:                https://github.com/xteve-project,
2020/06/17 14:51:43 [xTeVe] Git Branch:            master [xteve-project],
2020/06/17 14:51:43 [xTeVe] SSDP / DLNA:           true,
2020/06/17 14:51:43 [xTeVe] UUID:                  2020-06-OCBS-WO0LJD,
2020/06/17 14:51:43 [xTeVe] Tuner (Plex / Emby):   4,
2020/06/17 14:51:43 [xTeVe] EPG Source:            XEPG,
2020/06/17 14:51:43 [xTeVe] Plex Channel Limit:    480,
2020/06/17 14:51:43 [xTeVe] Backup Path:           /data/backup/,
2020/06/17 14:51:43 [xTeVe] Backup file:           /data/backup/xteve_auto_backup_20200617_1451.zip,
2020/06/17 14:51:43 [xTeVe] Download:              [feed],
2020/06/17 14:51:44 [xTeVe] Header filename:       liveTV.2020.06.17.m3u,
2020/06/17 14:51:44 [xTeVe] Check File:            [feed],
2020/06/17 14:51:44 [xTeVe] Save File:             [feed] [ID: MPB05B5JAPGHW2P10QQT],
2020/06/17 14:51:44 [xTeVe] Download:              http://www.xmltv.co.uk/feed/3364,
2020/06/17 14:51:44 [xTeVe] Check File:            http://www.xmltv.co.uk/feed/3364,
2020/06/17 14:51:44 [xTeVe] Save File:             http://www.xmltv.co.uk/feed/3364 [ID: XUH0C68EH5LLB1AWHBQ0],
2020/06/17 14:51:44 [xTeVe] All streams:           135,
2020/06/17 14:51:44 [xTeVe] Active streams:        135,
2020/06/17 14:51:44 [xTeVe] Filter:                0,
2020/06/17 14:51:44 [xTeVe] XEPG:                  Parse XMLTV file: XMLTV,
2020/06/17 14:51:44 [xTeVe] XEPG:                  Update database,
* * * * * FATAL ERROR * * * * *,
OS:   linux,
Arch: amd64,
Err:  assignment to entry in nil map,
panic.go:969 runtime.gopanic,
map_faststr.go:204 runtime.mapassign_faststr,
xepg.go:433 _/root/src.createXEPGDatabase,
xepg.go:78 _/root/src.buildXEPG,
config.go:259 _/root/src.StartSystem,
xteve.go:196 main.main,
proc.go:212 runtime.main,
asm_amd64.s:1374 runtime.goexit,
* * * * * * * * * * * * * * * *
```

**Comment by mar-mei** [comment]
Can you test that with the beta? There were some changes to the database. To do this, the update function in your Docker must work.
https://github.com/xteve-project/xTeVe#xteve-beta-branch

**Comment by ambersnow** [comment]
No idea what happened or why it got fixed but I tried booting it up again before switching it to beta and it magically fixed itself.
Thank you for the help though

**Comment by merrychrishna** [comment]
@mar-mei im stuck updating database too but it doesnt say fatal error in the console. i cant get the gui to come up. its happening on https://github.com/SCP002/xTeVe that version. should i get your version instead? and how can i downgrade it to your version?
